### PR TITLE
Add point (include commit new points)

### PR DESCRIPTION
**Pull request by tianqiyang**

### CODE REVIEW

**Review by randyfan — COMMENTED** [review]
Great work overall Steven, thank you!

There is an issue though that is due to version control. For TemporaryMeshManager.cpp,  ~1 month ago we decided to add a scene node for each added face/polyline, instead of just a single TemporaryPolyline/Mesh node.  It seems like you were adding your changes to a slightly outdated version of NOME, so those changes aren't reflected here.

Could you incorporate those recent changes? Since it's just a few functions, it may be easier to just copy and paste the functions from the updated version into yours: https://github.com/randyfan/NOME3/blob/master/Application/Scene/TemporaryMeshManager.cpp 
Also you may need to change AddPoint a little, creating a new node each time

**Comment by tianqiyang** [comment]
I incorporate those changes and update the functions I write.

**Comment by randyfan** [comment]
Thanks, I'll test out the changes later tonight

**Comment by tianqiyang** [comment]
Thanks！

**Pull request closed without merging**
